language: node_js
node_js:
  - '8'
deploy:
  provider: heroku
  api_key:
    secure: OBWvbJ+x3PM3hFb7COji9L4ciOyTbOyrfr9dkGy+z02x6PcA0/1Wdsua5OPTwPu79QO+Y+b+Q6AXRDjzob82ecseW3JYpYMtBv24Vl00QBbx9NKWp2DszpDLVgpkIScufDk34+uZ313kVG9W6RjQU4bfJRfDfQmI7IZwNZBDo0bfH4X0LqajZVdKmw8DdtbBacOM0HxQ2AcsA++dCUYLzRXbh7/zFs61W6gP5+MonMLkP4oy4t2T4W8YCRzQ/k1VhPPRQhvOdNHb1obpmGCZda9b5ug0XrwlYqQXm8gw3zyCwwoK7zAoUKf3kacTvIeECuvaJRqZGBbq6MOjqo5PDmPAVOunMRluvcA/i2UZYvQu+dum8WNQzAFuj3xJgPkaJKg6ew/z+UOX1vikmJibS0uXx/ka8jP749VDHKf3fUVmcxcReYJVxahVHP/7QhTuDEUbTMO4ekS7x4pYfTmz3iW8n5vp1+XZ4K8hjjjrohds4wfK+UpST4c1PjbyQXTt3TXBdS+ZzPpZdY1mZBxT0ufMAntffIa6biaWwnUbQsXfsBjQG5C59orTPUA9nfEBUcIj8iZxWsLjrDJbkEVSPPk6u4Mwr5NcIy6menRNEzom0oMRBBINmJnBpgBYPu4mPeUJAJ00Vb9Y/TY9uBeJlCTUSdmuJj99JJ14j9eFkcE=
  app: cpslab-bot
  on:
    repo: cpslab/cpsbot
notifications:
  slack:
    secure: PETD+vzrSJUaNImmrAVq/Dwns5jjcTld8228ncDria+NRP5iBazp8zsm1yGj/iFFYSgm1GaFIqIj2pSSHgkNEMrgQvqubpK6rVGbZH+TRlnGnZbVzXHZhc9nwaVLCrZ9ZSL92+rQKpfLzQk5aa2a3RBNmdU5Pms7ZyiUYbIAgScn6NF+RLqSun0SVk6BlJIHTQKBoui5lWfsdMT3tffpFgs+qBrbLgrwBmjJSAokDDjSvmE6wLvaAR4fCrsMjzvJgaAWffNCN0LDXBATK4ZursTx8vcbPfb3na6Dr6jitdBEO/grqElBqh/0yFtpDUNL6O2yuheaeJ9GLicMIqq7A9EaAQWfb4iqAWuWAyH+ZRi4FMjn4ymEYnAT2BQlFJ6xFDp7x3SXbEyDS0F2NtmpuTI8DGau5KI0I9xH2lmJav1gfDufXyZ0zUhY5IMLAZP4AqN4MIjgYuwoKHYQGVm3cQouO1824a+Qi4J1YmKHSpmYLMzlmKY+oSZ+6hW3rReL1TvvopOdQB0UpMYrX5ibm4xdEAbDG/x57rrYzLCQjt14fISQZiO3tGg5h2ttAvVW8sEnZNwhdg+92r4/SXLK64Pb7x+bw/6XTZ+pUMdh1WN+DFBY+jqK2J/0VpuXl/DDvzmpjUq9Lp0yF4/jUCQxko2PuKca0BDYaecduip2Sro=
